---

services:

  bot:
    build: .
    container_name: telegram-mc-cmd
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WORLD_NAME=${WORLD_NAME}
      - CUSTOM_PASSWORD=${CUSTOM_PASSWORD}
      - BASIC_PASSWORD=${BASIC_PASSWORD}
      - PLAYER_PASSWORD=${PLAYER_PASSWORD}
      - MODERATOR_PASSWORD=${MODERATOR_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./botData/:/app/botData
      - ./config.py/:/app/config.py
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bds_data:/bedrockData




  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bds
    restart: unless-stopped
    privileged: true
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TZ: "Europe/Rome"
      ENABLE_SSH: "TRUE"
    volumes:
      - ./bds_data:/data
    expose:
      # This is a reminder that this port is exposed to other containers in this compose file.
      - 2222
